Gemfile.lock, app/models/user.rb, config/routes.rb
Please review and merge. Thannnk you!
=> Created routes

app/controllers/joys_controller.rb, app/views/joys/index.html.rb
Hey I updated controller and created index for joys. Please have a look, and merge if it looks OK.
Thank you!
=> updated controller and created index for joys

app/controllers/joys_controller.rb, app/views/joys/index.html.rb, app/views/joys/show.html.rb
Updated joys_controller to have joy#show
Created joys/show.html.rb
Updated joys#index to add div
Please have a look and merge when you have time
=> created fortune cookie show

Gemfile, Gemfile.lock, app/controllers/joys_controller.rb, app/services/openai_service.rb, app/views/joys/show.html.erb, config/initializers/openai.rb
It works!!!!!  create a joy and get a fortune!!! pics on slack
=> WOOO HOO Chatgpt integrated into joys

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_navbar.scss, app/views/recommendations/index.html.erb, app/views/shared/_navbar.html.erb
Recommendations index is done (functionality/design) + links for my joys, my recos, my cards, my games have been added into the navbar button!
=> Reco index

app/assets/stylesheets/components/_buttons.scss, app/controllers/pages_controller.rb, app/controllers/recommendations_controller.rb, app/views/joys/index.html.erb, app/views/pages/home.html.erb, app/views/recommendations/show.html.erb
=> fixed revert issue hopefully plz

app/controllers/recommendations_controller.rb, app/javascript/controllers/star_rating_controller.js, app/views/recommendations/show.html.erb, config/routes.rb
Please review and merge when you have time
=> added rate function to recommendations

app/views/shared/_banner.html.erb, db/schema.rb
Please review and merge, thank you!
=> removed banner except for home page

app/assets/stylesheets/components/_cards.scss, app/views/shared/_banner.html.erb, db/schema.rb
Please review and merge.
I only edited the cards on card-home and the card-reco, if any further discussion or conclusion on how to change them, I can do it again.
=> Adjusted margin and spacing

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_cards.scss, app/javascript/controllers/inspire_button_controller.js, app/views/pages/home.html.erb
Inspire button is partially solved (now centered properly again). Need to work on the following with TA help:
- make sure the inspire prompt doesn't get cut inside the home card
- make sure toggle is working when click on the rainbow icon
=> Fonts colors

app/controllers/games_controller.rb, app/views/games/index.html.erb
started a first draft for games index
=> games index started

app/views/joys/_joy_form.html.erb
=> fixed merge mistake from joy form syntax error

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_navbar.scss, app/controllers/gamecards_controller.rb, app/views/gamecards/index.html.erb, app/views/shared/_navbar.html.erb
Latest version of carousel and also fixed issues with the padding in navbar + remove the import line of the cursive font so it should not appear anymore in heroku (hopefully)
=> Gamecards index

config/environments/production.rb
Switched from HPPT (unsecure) to Force HTTPS (secured)
=> updated secure SSL configuration and forced SSL

app/assets/stylesheets/components/_footer.scss
I fixed footer to the bottom for all pages, and changed the height of footer from 100px tp 80px
Please review and merge
=> fixed footer to the bottom

app/assets/stylesheets/components/_buttons.scss
it works, long amd short prompts
=> btn inspire fixed

app/jobs/gamecard_job.rb, app/services/openai_service.rb
Fixed the error to create joy/get gamecards with Saki!
=> Carousel front

app/controllers/pages_controller.rb
Fixed prompt for weekly recs to make it 50 word limit and more responsive to user's joys = more personalized
=> tweaked the rec prompt to 50 words + more responsive to joy content

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_footer.scss, app/javascript/controllers/star_rating_controller.js, app/views/gamecards/index.html.erb, app/views/joys/_joy_form.html.erb, app/views/layouts/application.html.erb, config/locales/simple_form.en.yml
I have fixed footer and removed star rater text, also changed oversized Recommendation font, as well as carousel (repositioned)
Please review and merge
=> fixed footer and removed star rater text

app/controllers/pages_controller.rb, app/javascript/controllers/fortune_cookie_controller.js, app/views/pages/home.html.erb, app/views/shared/_banner.html.erb
1 btn displayed only when rec created + disppaears after clicked on, links you to rec index
=> Update weekly btn logic only1

app/controllers/pages_controller.rb, app/javascript/controllers/fortune_cookie_controller.js, app/views/pages/home.html.erb, app/views/shared/_banner.html.erb, app/views/shared/_navbar.html.erb
functional sign out just needs alert that says you signed out
=> Sign out function

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_cards.scss
I have changed reco font size and carousel position to fit with 320*456
Please review and merge
=> changed reco font size and carousel position to fit with 320*456

app/assets/stylesheets/application.scss, app/views/recommendations/index.html.erb
the search icon is now clickable
=> Searchbar nickname

app/assets/stylesheets/components/_buttons.scss, db/seeds.rb
seeds = realistic reply + btn inspire width updated
=> fixed btn inspire width + realistic rec seed

app/assets/stylesheets/components/_stars.scss, app/javascript/controllers/star_rating_controller.js
=> centered stars

app/controllers/gamecards_controller.rb, app/controllers/joys_controller.rb, app/controllers/recommendations_controller.rb, db/schema.rb
Rec + JOYS + cards all display in their index from most recent to oldest now. We can adjust code to not be in descending order for joys and cards if rather not have this lmk. thanks
=> Recomendation index new to old update

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_banner.scss, app/javascript/controllers/star_rating_controller.js
I ahve removed balck label and changed h1 h2 shadow
Please merge
=> removed balck label and changed h1 h2 shadow

public/404.html, public/500.html
error pages 404 and 500 customized
=> error pages customized

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_cards.scss
added css lines to handle blue underline
=> updated links underline from new games

app/assets/stylesheets/components/_banner.scss
I made the borders of the letters in Joyjot title a bit darker for more visibility
=> title border made darker

app/assets/stylesheets/components/_banner.scss
=> title even darker
